"""
src/core/event_bus.py
Lightweight, zero-framework asynchronous event bus with strongly-typed Pydantic v2
event schemas and isolated error boundaries.
"""

import asyncio
import logging
import uuid
from datetime import datetime, timezone
from typing import (
    Any,
    Awaitable,
    Callable,
    Dict,
    List,
    Optional,
    Type,
    TypeVar,
    Union,
)
from pydantic import BaseModel, Field

logger = logging.getLogger("event_bus")


# ------------------------------------------------------------------------------
# 1. Typed Event Schemas (Pydantic v2)
# ------------------------------------------------------------------------------

class BaseEvent(BaseModel):
    """Base event model with automatic UUID, UTC timestamp, and typed event discriminator."""

    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Globally unique identifier for the event",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the event was generated",
    )
    event_type: str = Field(
        description="String discriminator identifier for event routing",
    )

    model_config = {"arbitrary_types_allowed": True}


class MarketTickEvent(BaseEvent):
    """Real-time market quote tick for an underlying instrument or options contract."""

    event_type: str = "MarketTickEvent"
    symbol: str = Field(description="Ticker or OCC option contract identifier")
    bid: float = Field(ge=0.0, description="Best bid price")
    ask: float = Field(ge=0.0, description="Best ask price")
    last_price: float = Field(ge=0.0, description="Last traded price")
    volume: int = Field(default=0, ge=0, description="Cumulative or tick volume")

    @property
    def mid_price(self) -> float:
        """Calculates arithmetic midpoint of the bid-ask spread."""
        return (self.bid + self.ask) / 2.0

    @property
    def spread(self) -> float:
        """Calculates absolute bid-ask spread."""
        return self.ask - self.bid

    @property
    def slippage_pct(self) -> float:
        """Calculates bid-ask spread as a fraction of midpoint."""
        mid = self.mid_price
        return (self.spread / mid) if mid > 0 else 0.0


class OptionsChainSnapshotEvent(BaseEvent):
    """Aggregated snapshot of an option chain for volatility and strike analysis."""

    event_type: str = "OptionsChainSnapshotEvent"
    symbol: str = Field(description="Underlying root symbol (e.g. SPY, QQQ)")
    underlying_price: float = Field(gt=0.0, description="Current price of the underlying asset")
    expiration_dates: List[str] = Field(description="List of available expiration dates (YYYY-MM-DD)")
    strikes: List[float] = Field(description="Sorted list of available strike prices")
    contracts_count: int = Field(ge=0, description="Total contracts discovered in the chain")
    snapshot_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Detailed contract dictionaries mapping OCC symbol to quote snapshots",
    )


class SignalEvent(BaseEvent):
    """Quantitative signal generated by the regime detector or technical indicators."""

    event_type: str = "SignalEvent"
    symbol: str = Field(description="Underlying ticker symbol")
    regime: str = Field(description="Classified market regime (e.g. HIGH_IV_RANGEBOUND, HIGH_IV_TRENDING)")
    signal_type: str = Field(description="Suggested structure: BULL_PUT, BEAR_CALL, IRON_CONDOR, DEBIT_SPREAD")
    confidence: float = Field(ge=0.0, le=1.0, description="Signal confidence score between 0.0 and 1.0")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Supporting metrics: IVR, IVP, ADX, trend slope, historical volatility",
    )


class OrderProposalEvent(BaseEvent):
    """Trade hypothesis formulated by LLM Strategist awaiting deterministic risk authorization."""

    event_type: str = "OrderProposalEvent"
    proposal_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique proposal tracking ID",
    )
    symbol: str = Field(description="Underlying ticker symbol")
    strategy_name: str = Field(description="Name of defined-risk spread (e.g. Bull Put Credit Spread)")
    legs: List[Dict[str, Any]] = Field(description="Ordered list of spread legs with OCC symbols, sides, and deltas")
    target_credit: float = Field(ge=0.0, description="Expected net credit per share (spread pricing)")
    max_profit: float = Field(ge=0.0, description="Total max profit in dollars for proposed quantity")
    max_loss: float = Field(ge=0.0, description="Total max loss / capital at risk in dollars")
    required_margin: float = Field(ge=0.0, description="Estimated margin requirement in dollars")
    ivr: float = Field(description="Implied Volatility Rank of underlying at creation")
    dte: int = Field(ge=0, description="Days to expiration of front leg")
    thesis: str = Field(description="LLM-generated human-readable trade justification")
    source_model: str = Field(description="Model that proposed the trade (e.g. Gemini-3.8-Flash, Qwen-2.5-72B)")
    is_approved: bool = Field(default=False, description="Set True only after RiskGatekeeper authorization")


class OrderExecutionEvent(BaseEvent):
    """Order routing event dispatched upon submitting an order to Alpaca."""

    event_type: str = "OrderExecutionEvent"
    order_id: str = Field(description="Alpaca order UUID")
    client_order_id: str = Field(description="Idempotent client order ID")
    symbol: str = Field(description="Underlying ticker or primary contract OCC symbol")
    status: str = Field(description="Current status: PENDING_NEW, ACCEPTED, REJECTED, CANCELED")
    order_type: str = Field(description="Order class: limit, market, mleg")
    limit_price: Optional[float] = Field(default=None, description="Submitted limit price")
    raw_response: Dict[str, Any] = Field(
        default_factory=dict,
        description="Raw Alpaca API order response payload",
    )


class FillEvent(BaseEvent):
    """Execution fill confirmation indicating position opened or closed."""

    event_type: str = "FillEvent"
    order_id: str = Field(description="Alpaca order UUID")
    client_order_id: str = Field(description="Idempotent client order ID")
    symbol: str = Field(description="Underlying ticker or contract OCC symbol")
    fill_price: float = Field(description="Average execution fill price")
    quantity: int = Field(gt=0, description="Number of contracts or units filled")
    execution_fees: float = Field(default=0.0, ge=0.0, description="Exchange and regulatory fees")
    filled_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the execution fill",
    )
    legs_filled: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Individual leg execution prices and contract details",
    )


# Generic Event TypeVar for strong subscriber typing
E = TypeVar("E", bound=BaseEvent)
EventHandler = Union[Callable[[E], Awaitable[None]], Callable[[E], None]]


# ------------------------------------------------------------------------------
# 2. Async Event Bus Implementation
# ------------------------------------------------------------------------------

class EventBus:
    """
    Lightweight, asynchronous Pub/Sub Event Bus.
    Features:
    - Strongly-typed topic subscriptions by Event Class or event_type string.
    - Background queue worker for non-blocking asynchronous event decoupling.
    - Isolated error boundaries: a crashing handler never crashes the event loop or other subscribers.
    - Full telemetry tracking: published, delivered, and error counts.
    """

    def __init__(self, max_queue_size: int = 10000) -> None:
        self._subscribers: Dict[str, List[Callable[[Any], Any]]] = {}
        self._queue: asyncio.Queue[Optional[BaseEvent]] = asyncio.Queue(maxsize=max_queue_size)
        self._worker_task: Optional[asyncio.Task[None]] = None
        self._is_running: bool = False

        # Telemetry metrics
        self.events_published: int = 0
        self.events_delivered: int = 0
        self.errors_caught: int = 0

    def subscribe(
        self,
        event_cls: Union[Type[E], str],
        handler: Callable[[Any], Any],
    ) -> None:
        """
        Subscribes a synchronous or asynchronous callback to a specific event type.
        """
        event_type = event_cls if isinstance(event_cls, str) else event_cls.__name__
        if event_type not in self._subscribers:
            self._subscribers[event_type] = []
        if handler not in self._subscribers[event_type]:
            self._subscribers[event_type].append(handler)
            logger.debug("Subscribed %s to %s", getattr(handler, "__name__", str(handler)), event_type)

    def unsubscribe(
        self,
        event_cls: Union[Type[E], str],
        handler: Callable[[Any], Any],
    ) -> None:
        """
        Unsubscribes a callback from an event type.
        """
        event_type = event_cls if isinstance(event_cls, str) else event_cls.__name__
        if event_type in self._subscribers and handler in self._subscribers[event_type]:
            self._subscribers[event_type].remove(handler)
            logger.debug("Unsubscribed %s from %s", getattr(handler, "__name__", str(handler)), event_type)

    def on(self, event_cls: Union[Type[E], str]) -> Callable[[Callable[[Any], Any]], Callable[[Any], Any]]:
        """
        Decorator pattern for registering event subscribers:
        @event_bus.on(MarketTickEvent)
        async def on_tick(event: MarketTickEvent):
            ...
        """
        def decorator(handler: Callable[[Any], Any]) -> Callable[[Any], Any]:
            self.subscribe(event_cls, handler)
            return handler
        return decorator

    async def publish(self, event: BaseEvent) -> None:
        """
        Enqueues an event for asynchronous processing by the worker loop.
        Non-blocking to the caller.
        """
        self.events_published += 1
        await self._queue.put(event)

    async def dispatch(self, event: BaseEvent) -> None:
        """
        Synchronously (inline) dispatches an event to all subscribed handlers with error isolation.
        Useful for deterministic testing or immediate event execution.
        """
        event_type = event.event_type
        handlers = self._subscribers.get(event_type, []).copy()

        # Also dispatch to wildcard listeners if registered
        wildcard_handlers = self._subscribers.get("*", []).copy()
        all_handlers = handlers + wildcard_handlers

        for handler in all_handlers:
            try:
                if asyncio.iscoroutinefunction(handler):
                    await handler(event)
                else:
                    handler(event)
                self.events_delivered += 1
            except Exception as exc:
                self.errors_caught += 1
                handler_name = getattr(handler, "__name__", str(handler))
                logger.error(
                    "Error in event handler '%s' processing '%s': %s",
                    handler_name,
                    event_type,
                    exc,
                    exc_info=True,
                )

    async def start(self) -> None:
        """Starts the background worker queue consumer task."""
        if self._is_running:
            return
        self._is_running = True
        self._worker_task = asyncio.create_task(self._process_queue())
        logger.info("EventBus background worker started.")

    async def stop(self) -> None:
        """Gracefully drains the queue and stops the worker task."""
        if not self._is_running:
            return
        self._is_running = False
        await self._queue.put(None)  # Sentinel to terminate worker
        if self._worker_task:
            await self._worker_task
            self._worker_task = None
        logger.info("EventBus background worker stopped.")

    async def wait_until_idle(self) -> None:
        """Waits until all pending events in the queue have been fully processed."""
        await self._queue.join()

    async def _process_queue(self) -> None:
        """Internal worker loop consuming events from the queue."""
        while True:
            event = await self._queue.get()
            if event is None:
                self._queue.task_done()
                break
            try:
                await self.dispatch(event)
            finally:
                self._queue.task_done()

    def clear(self) -> None:
        """Clears all subscribers and resets telemetry metrics."""
        self._subscribers.clear()
        self.events_published = 0
        self.events_delivered = 0
        self.errors_caught = 0


# Global singleton event bus instance
event_bus: EventBus = EventBus()
